### ISSUE TITLE
'CacheService' is not exported by ./node_modules/@valo/cache/dist/index.js

### ISSUE THREAD

**Issue by vinaunder** [ValoIntranet/indexeddb-cache#2]
Hi,
I´m Using "@valo/cache": "0.0.1",

I have got this error
`'CacheService' is not exported by ./node_modules/@valo/cache/dist/index.js`

this is my TS file
import { IMenu } from "./../interfaces/appLists.interfaces";
import { Web } from "@pnp/sp/webs";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import { SPFXutils } from "./../services/SPFXutils";
import { CacheService, DateHelper, DateInterval } from '@valo/cache';

export const useMenu = async () => {
  (async () => {
    await cache.init();
  })();

  const cache = new CacheService(`menuhorizontal`);

  const getMenu = async (): Promise<IMenu[]> => {
    try {
      return await cache.get(`menuhorizontal`);
    } catch (error) {
      getItensPai().then(async (r) => {
        await cache.put(`menuhorizontal`, r, DateHelper.dateAdd(Date(), DateInterval.minute, 1));
        return r;
      });
    }
  };

  const getItensPai = async(): Promise<IMenu[]> => {
    try {
      var menu: IMenu[] = [];
      const w = Web(this.siteUrl);
      const queryOptions = `<QueryOptions><ViewAttributes Scope='RecursiveAll'/></QueryOptions>`;
      var query = `<Query><Where><IsNull><FieldRef Name="pai" /></IsNull></Where><OrderBy><FieldRef Name='SANOrdem1' Ascending='True' /></OrderBy></Query>`;
      let r = await w.lists.getByTitle(this.listName).renderListDataAsStream({
        ViewXml: `<view>${query}${queryOptions}</view>`,
      });
      if (r.Row.length > 0) {
        for (let i = 0; i < r.Row.length; i++) {
          const element = r.Row[i];
          //busca filho
          var menufilho: IMenu[] = await getItensFilho(element.ID);
          var item: IMenu = {
            Id: element.ID,
            Title: element.Title,
            SANLink:
              element.SANLinkMult != "" ? element.SANLinkMult : element.SANLink,
            SANNewWindown: element.SANNewWindown,
            SANOrdem1: element.SANOrdem1,
            SANIcon: new SPFXutils().extractIMGUrl(element.SANIcon, "menu"),
            Filho: menufilho,
            isActive: element.SANLink === window.location.pathname,
            openie: element.openIE,
          };
          menu.push(item);
        }
      }
      return menu;
    } catch (error) {
      console.error(error);
    }
  }

  const getItensFilho = async(pai: string): Promise<IMenu[]> => {
    try {
      var menufilho: IMenu[] = [];
      const w = Web(this.siteUrl);
      const queryOptions = `<QueryOptions><ViewAttributes Scope='RecursiveAll'/></QueryOptions>`;
      var query =
        `<Query><Where><Eq><FieldRef Name="pai" LookupId='TRUE' /><Value Type="Lookup">` +
        pai +
        `</Value></Eq></Where><OrderBy><FieldRef Name='SANOrdem1' Ascending='True' /></OrderBy></Query>`;
      let items = await w.lists
        .getByTitle(this.listName)
        .renderListDataAsStream({
          ViewXml: `<view>${query}${queryOptions}</view>`,
        });
      if (items.Row.length > 0) {
        for (let i = 0; i < items.Row.length; i++) {
          const element = items.Row[i];
          var menusubfilho: IMenu[] = await getItensFilho(element.ID);
          var item: IMenu = {
            Id: element.ID,
            Title: element.Title,
            SANLink:
              element.SANLinkMult != "" ? element.SANLinkMult : element.SANLink,
            SANNewWindown: element.SANNewWindown,
            SANOrdem1: element.SANOrdem1,
            SANIcon: new SPFXutils().extractIMGUrl(element.SANIcon, "menu"),
            Filho: menusubfilho,
            isActive: element.SANLink === window.location.pathname,
            openie: element.openIE,
          };
          menufilho.push(item);
        }
      }
      return menufilho;
    } catch (e) {
      console.log(e);
    }
  }

  return {
    getMenu,
  };
};

**Comment by estruyf** [comment]
Can you verify the `index.js` file? It should contain a `(require("./services"), exports);` export.

**Comment by vinaunder** [comment]
> Can you verify the `index.js` file? It should contain a `(require("./services"), exports);` export.

![image](https://user-images.githubusercontent.com/8633332/104021554-e1418f80-51b6-11eb-89f5-ac499ed7dc5b.png)

**Comment by estruyf** [comment]
Looks fine, which version of node / typescript are you using?

Does VSCode find the definition of the referenced service?

**Comment by vinaunder** [comment]
> Looks fine, which version of node / typescript are you using?
> 
> Does VSCode find the definition of the referenced service?

node version - v10.18.0
and i´m using stenciljs - 1.17.4

VSCode finds the definition of the reference

a delete de package-lock and run npm i again
and Works 👍

**Comment by estruyf** [comment]
Oh, maybe a cache issue somewhere. I'll close it, happy you found it!
